<?xml version="1.0"?>
<package format="2">
  <name>ccom_planner</name>
  <version>0.0.0</version>
  <description>A project11_navigation planner for Dubins vehicles based on A*</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <depend>behaviortree_cpp</depend>
  <depend>dubins_curves</depend>
  <depend>geometry_msgs</depend>
  <depend>project11_navigation</depend>
  <depend>rclcpp</depend>
  <depend>tf2</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
